name: Python application with Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: "k8s/Modulo 37"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry 

      - name: Install httpx
        run: pip install httpx

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-root --no-interaction
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: poetry run pytest

      - name: Debug files
        run: |
         pwd
         ls -la
         find . -name "Dockerfile" -o -name "dockerfile"  

      - name: Build Docker image
        run: docker build -t fastapi-app:latest .

      - name: Test Docker container
        run: |
          docker run -d --name fastapi-test -p 8000:8000 fastapi-app:latest
          sleep 10
          docker ps
          docker logs fastapi-test
          docker stop fastapi-test